SELECT * FROM fact

SELECT * FROM Product

SELECT * FROM Location

--1.Display the number of states present in the location table.

SELECT COUNT(DISTINCT State) FROM Location

--2.How many products are of regular type.

SELECT COUNT(Type) FROM Product
WHERE Type = 'Regular'

--3.How much Spending has been done on marketing of product ID 1?

SELECT SUM(Marketing) FROM fact 
WHERE ProductId = 1

--4.What is the minimum sales of a product?

SELECT MIN(Sales) FROM fact

--5.Display the max cost of good sold(COGS).

SELECT MAX(Budget_COGS) FROM fact

--6.Display the details of the product where product type is coffee.

SELECT * FROM Product 
where Product_Type = 'Coffee'

--7.Display the Details where total expenses are greater than 40.

SELECT *  FROM fact
WHERE Total_Expenses > 40

--8.What is the average sales in area code 719?

SELECT AVG(Sales) FROM fact
WHERE Area_Code = 719

--9.Find out the total profit generated by colorado state.

SELECT SUM(Profit) FROM fact
JOIN Location ON fact.Area_Code = Location.Area_Code
WHERE State = 'Colorado'

--10.Display the average inventory for each product ID.

SELECT ProductId, AVG(Inventory) AS Avearge_Inventory
FROM fact
GROUP BY ProductId

--11.Display state in a sequential order in a location table.

SELECT * FROM Location
ORDER BY State ASC

--12.

SELECT ProductId,AVG(Budget_Margin) FROM fact
GROUP BY ProductId 
HAVING AVG(Budget_Margin) >100

--13.

SELECT SUM(Sales) FROM fact 
WHERE Date = '2010-01-01'

--14.

SELECT ProductId, Date, AVG(Total_Expenses) AS Average_Expenses FROM fact
GROUP BY ProductId, Date

--15.

SELECT 
f.Date,
f.ProductId, 
p.Product_Type,
p.Product,
f.Sales,
f.Profit,
l.State,
l.Area_Code
FROM fact AS f
JOIN Product AS p ON f.ProductId = p.ProductId
JOIN Location As l ON f.Area_Code = l.Area_Code

--16.

SELECT * 
, DENSE_RANK() OVER(order by Sales DESC) AS Dense_Rank
FROM fact

--17.

SELECT 
l.State,
SUM(f.Profit) AS total_Profits,
SUM(f.Sales) AS total_Sales
FROM fact As f
JOIN Location AS l ON f.Area_Code = l.Area_Code
GROUP BY State

--18.

SELECT 
l.State,
SUM(f.Profit) AS total_Profits,
SUM(f.Sales) AS total_Sales,
p.Product
FROM fact As f
JOIN Location AS l ON f.Area_Code = l.Area_Code
JOIN Product AS p ON f.ProductId = p.ProductId
GROUP BY State, Product

--19.

SELECT ProductId, Sales,
Sales*1.05 AS Sales_Increase
FROM fact

--20.

SELECT Max(f.Profit) AS Max_Product,
p.ProductId,
p.Product_Type
FROM fact AS f
JOIN Product AS p ON f.ProductId = P.ProductId
GROUP BY p.Product_Type, p.ProductId

--21.

CREATE OR ALTER PROCEDURE FETCH_PRODUCT
@PRODUCT_TYPE VARCHAR(30)
AS
BEGIN
SELECT * FROM Product
WHERE Product_Type = @PRODUCT_TYPE
END

EXEC FETCH_PRODUCT 'COFFEE'

--22.

SELECT Total_Expenses,
CASE 
WHEN Total_Expenses < 60
THEN 'PROFIT'
ELSE 'LOSS'
END AS PROFIT_LOSS
FROM fact

--23.

SELECT DATEPART(WEEK,F.Date)AS WEEKLY,
f.Date,
f.ProductId,
SUM(f.Sales) AS Total_Sales
FROM fact AS f
GROUP BY ROLLUP(DATEPART(WEEK,f.Date),f.Date, f.ProductId)

--24.

SELECT Area_Code FROM fact
UNION 
SELECT Area_Code FROM Location

SELECT Area_Code FROM fact
INTERSECT 
SELECT Area_Code FROM Location

--25.

CREATE OR ALTER FUNCTION FN_Product
(
@Product_Type VARCHAR(20)
)
RETURNS TABLE
AS
RETURN
(
SELECT * FROM PRODUCT
WHERE 
Product_Type=@Product_Type
)

SELECT * FROM FN_Product('Coffee')

--26.

BEGIN TRANSACTION 
UPDATE PRODUCT 
SET Product_Type='Tea'
WHERE Product_Type='Coffee'

SELECT * FROM Product WHERE Product_Type='Tea'
ROLLBACK TRANSACTION

--27.

SELECT Date, ProductId, Sales FROM fact 
WHERE Total_Expenses BETWEEN 100 AND 200

--28.

DELETE FROM Product WHERE Type = 'Regular'

--29.

SELECT Product,
ASCII(SUBSTRING(Product,5,1)) AS FIFTH_ASCII
FROM Product

SELECT UPPER(Product)
FROM Product

SELECT LOWER(Product)
FROM Product